### PR TITLE
Auto complete price for current item in new parcel

### PR DESCRIPTION
**Pull request by thib44**

### CODE REVIEW

**Comment by thib44** [comment]
@Aquaj Done

**Comment by thib44** [comment]
@Aquaj Done

**Comment by Aquaj** [comment]
Could you fix conflicts ?

**Comment by thib44** [comment]
@Aquaj Yes done

**Comment by thib44** [comment]
@Aquaj Wich changes is requested ?

**Comment by burisu** [comment]
It's OK, @Aquaj already made the pull on master

**Pull request merged**
